# Generated by Django 2.2.1 on 2021-06-01 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('classes', models.CharField(max_length=255)),
                ('total', models.IntegerField()),
                ('modules', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('full_question', models.CharField(max_length=255)),
                ('questionOnly', models.CharField(max_length=255)),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('option_4', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=5)),
                ('chapter', models.CharField(max_length=255)),
                ('modules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_modules', to='apis.Modules')),
            ],
        ),
        migrations.CreateModel(
            name='ModulesStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('modules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulesstatus_modules', to='apis.Modules')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_user', to='apis.User')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history_question', to='apis.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history_user', to='apis.User')),
            ],
        ),
    ]
